export type Technique =
  | "scroll-driven"
  | "real-time-interactivity"
  | "product-configuration"
  | "immersive-storytelling";

export type Industry =
  | "Fashion"
  | "Automotive"
  | "Music"
  | "Architecture"
  | "Gaming"
  | "Portfolio"
  | "Tech"
  | "Editorial"
  | "Sports"
  | "Beverage"
  | "Film"
  | "Crypto";

export type Award = "Awwwards SOTD" | "Awwwards SOTM" | "Codrops Hot" | "FWA" | "CSSDA" | "OFFF Pick";

export type Site = {
  id: string;
  name: string;
  studio: string;
  url: string;
  year: 2025 | 2026;
  techniques: Technique[];
  industry: Industry;
  awards: Award[];
  mobilePerf: number; // Lighthouse-style 0-100
  loadKb: number; // bundle weight in KB
  fps: number; // mid-range mobile fps target
  summary: string;
  stack: string[];
  palette: [string, string, string]; // for the procedural thumbnail
  thumbStyle: "orb" | "ribbon" | "grid" | "noise" | "shards" | "wave" | "particles" | "tunnel";
};

export const SITES: Site[] = [
  {
    id: "atelier-rhei",
    name: "Atelier Rhei — Liquid Couture",
    studio: "Lusion × Maison Margiela",
    url: "https://atelier-rhei.example",
    year: 2026,
    techniques: ["immersive-storytelling", "scroll-driven"],
    industry: "Fashion",
    awards: ["Awwwards SOTM", "FWA"],
    mobilePerf: 86,
    loadKb: 612,
    fps: 58,
    summary:
      "Scroll-locked GLB ferrofluid that morphs into garments via MeshTransmissionMaterial and a custom curl-noise vertex shader. KTX2 textures and Draco-compressed geometry keep the first paint under 1.2s on mid-range Android.",
    stack: ["Three.js r170", "GPGPU FBO", "MeshTransmissionMaterial", "KTX2", "Draco", "GSAP ScrollTrigger"],
    palette: ["#0a0a1a", "#8a6bff", "#f6e7ff"],
    thumbStyle: "orb",
  },
  {
    id: "lotus-emeira",
    name: "Lotus Emeira Configurator",
    studio: "Active Theory",
    url: "https://lotuscars.example/emeira",
    year: 2026,
    techniques: ["product-configuration", "real-time-interactivity"],
    industry: "Automotive",
    awards: ["Awwwards SOTD", "FWA"],
    mobilePerf: 78,
    loadKb: 1840,
    fps: 50,
    summary:
      "Real-time PBR configurator running WebGPU on capable devices and falling back to instanced WebGL2. Variant geometry is streamed as USDZ proxies; HDR IBL is baked into 2K equirect with on-device tonemap LUT.",
    stack: ["WebGPU", "Three.js TSL", "USDZ proxy", "Compressed HDR", "Worker-based BVH"],
    palette: ["#101418", "#d4a24c", "#f4f4f0"],
    thumbStyle: "shards",
  },
  {
    id: "okami-records",
    name: "Okami Records — Side B",
    studio: "Studio Yorktown",
    url: "https://okami.example",
    year: 2026,
    techniques: ["real-time-interactivity", "immersive-storytelling"],
    industry: "Music",
    awards: ["Codrops Hot", "Awwwards SOTD"],
    mobilePerf: 91,
    loadKb: 410,
    fps: 60,
    summary:
      "Audio-reactive raymarched SDF terrain driven by FFT bins; the cursor warps a Worley-noise heightfield via a compute pass. Falls back to 2D canvas spectrogram below 30fps mid-frame budget.",
    stack: ["Three.js", "WebAudio FFT", "Raymarching shader", "Compute fallback", "WASM resampler"],
    palette: ["#000000", "#ff3b6b", "#9affd8"],
    thumbStyle: "wave",
  },
  {
    id: "kengo-pavilion",
    name: "Kengo Kuma — Floating Pavilion",
    studio: "Resn",
    url: "https://kengo-pavilion.example",
    year: 2026,
    techniques: ["scroll-driven", "immersive-storytelling"],
    industry: "Architecture",
    awards: ["Awwwards SOTM", "CSSDA"],
    mobilePerf: 82,
    loadKb: 980,
    fps: 56,
    summary:
      "Twelve thousand instanced cedar slats deform along a Catmull-Rom curve as the user scrolls. Real-time CSM cascades give crisp shadows at three depth bands; light probes are baked per chapter.",
    stack: ["Instanced meshes", "CSM shadows", "Bezier scroll spine", "Lightmap atlas", "Lenis smooth scroll"],
    palette: ["#1b1410", "#d8a86b", "#f1ead8"],
    thumbStyle: "ribbon",
  },
  {
    id: "nova-frontier",
    name: "Nova Frontier — Open Beta",
    studio: "Active Theory",
    url: "https://novafrontier.example",
    year: 2026,
    techniques: ["real-time-interactivity", "immersive-storytelling"],
    industry: "Gaming",
    awards: ["FWA", "Awwwards SOTD"],
    mobilePerf: 74,
    loadKb: 2640,
    fps: 48,
    summary:
      "Browser-native MMO lobby with 80 concurrent avatars rendered via skeletal-instanced GPU skinning. Network state runs on a CRDT in a SharedWorker; renderer never sees more than 4ms of CPU per frame.",
    stack: ["GPU skinning", "SharedWorker CRDT", "Geometry-shader trails", "Bloom + TAA", "WebTransport"],
    palette: ["#06030d", "#5dd0ff", "#ff6ad5"],
    thumbStyle: "particles",
  },
  {
    id: "bruno-2026",
    name: "Bruno Simon — Folio 2026",
    studio: "Bruno Simon",
    url: "https://bruno-simon.example",
    year: 2026,
    techniques: ["real-time-interactivity", "immersive-storytelling"],
    industry: "Portfolio",
    awards: ["Awwwards SOTM", "FWA", "Codrops Hot"],
    mobilePerf: 88,
    loadKb: 720,
    fps: 60,
    summary:
      "Open-world drivable folio rebuilt on Rapier physics WASM. Decals and projected text labels read at any zoom; LOD swaps geometry at 24m to keep mid-range thermals in check.",
    stack: ["Rapier WASM", "Reflector portals", "Decal projection", "LOD chains", "Touch joystick"],
    palette: ["#0e1326", "#ffd45e", "#ff7a5c"],
    thumbStyle: "tunnel",
  },
  {
    id: "patagonia-tide",
    name: "Patagonia — Tide Report",
    studio: "North Kingdom",
    url: "https://patagonia.example/tide",
    year: 2026,
    techniques: ["scroll-driven", "immersive-storytelling"],
    industry: "Editorial",
    awards: ["Awwwards SOTD", "CSSDA"],
    mobilePerf: 94,
    loadKb: 380,
    fps: 60,
    summary:
      "Editorial long-read with a single GPGPU ocean shader threaded through eight chapters. Gerstner waves blend with a flowmap-driven foam pass; the entire scene is one 38KB shader plus tiles.",
    stack: ["Gerstner GPGPU", "Flowmap foam", "ScrollTimeline API", "View Transitions", "Reduced motion"],
    palette: ["#08161d", "#3fd0c9", "#f4f7e5"],
    thumbStyle: "wave",
  },
  {
    id: "apple-vp-hub",
    name: "Apple — Vision Pro Hub",
    studio: "Apple Marcom",
    url: "https://apple.example/vp",
    year: 2026,
    techniques: ["scroll-driven", "product-configuration"],
    industry: "Tech",
    awards: ["Awwwards SOTD"],
    mobilePerf: 92,
    loadKb: 560,
    fps: 60,
    summary:
      "Pinned-canvas scrollytell with frame-perfect mesh morphs. Custom ETC1S/UASTC tiered textures, hand-tuned MikkTSpace tangents, and HEVC alpha video composited on top of the GL canvas.",
    stack: ["Pinned canvas", "MikkTSpace tangents", "HEVC alpha overlay", "View Transitions", "AR Quick Look"],
    palette: ["#0a0a0a", "#e5e5e7", "#5ac8fa"],
    thumbStyle: "grid",
  },
  {
    id: "nike-airzero",
    name: "Nike Air Zero — Build Yours",
    studio: "AKQA",
    url: "https://nike.example/airzero",
    year: 2026,
    techniques: ["product-configuration", "real-time-interactivity"],
    industry: "Fashion",
    awards: ["FWA", "Awwwards SOTD"],
    mobilePerf: 84,
    loadKb: 1120,
    fps: 58,
    summary:
      "Per-panel material swap with anisotropic suede and Sheen BRDF. Color picker writes to a texture array; a single draw call renders all 23 panel meshes via instanced attributes.",
    stack: ["Anisotropic + Sheen BRDF", "Texture array swap", "Instanced attributes", "Color-managed sRGB"],
    palette: ["#111", "#ff4d00", "#fafafa"],
    thumbStyle: "shards",
  },
  {
    id: "stripe-press-orbit",
    name: "Stripe Press — Orbit",
    studio: "Stripe Press",
    url: "https://press.stripe.example/orbit",
    year: 2025,
    techniques: ["scroll-driven", "immersive-storytelling"],
    industry: "Editorial",
    awards: ["Awwwards SOTD", "Codrops Hot"],
    mobilePerf: 96,
    loadKb: 240,
    fps: 60,
    summary:
      "Two hundred essays mapped to orbital nodes. Lightweight 6KB shader draws connecting bezier curves on a single quad; 60fps on a 2019 budget phone.",
    stack: ["Single-quad shader", "Bezier on GPU", "CSS scroll-timeline", "Lazy chapter mount"],
    palette: ["#0b0d12", "#8b8aff", "#fffdfa"],
    thumbStyle: "noise",
  },
  {
    id: "fc-tokyo-pulse",
    name: "FC Tokyo — Pulse 26/27",
    studio: "Tha Ltd.",
    url: "https://fctokyo.example/pulse",
    year: 2026,
    techniques: ["real-time-interactivity", "scroll-driven"],
    industry: "Sports",
    awards: ["Awwwards SOTM", "CSSDA"],
    mobilePerf: 80,
    loadKb: 880,
    fps: 54,
    summary:
      "Stadium roar visualized as a city-scale GPU particle field. Crowd noise from match audio drives a SPH-style fluid sim in a 256×256 FBO ping-pong pass.",
    stack: ["FBO ping-pong", "Audio-reactive curl", "Custom additive material", "Service-worker preloader"],
    palette: ["#02020a", "#ff2e63", "#0066ff"],
    thumbStyle: "particles",
  },
  {
    id: "soju-spirits",
    name: "Soju Spirits — 24 Distilleries",
    studio: "Hello Monday",
    url: "https://sojuspirits.example",
    year: 2026,
    techniques: ["scroll-driven", "immersive-storytelling"],
    industry: "Beverage",
    awards: ["Codrops Hot", "Awwwards SOTD"],
    mobilePerf: 89,
    loadKb: 510,
    fps: 60,
    summary:
      "Glass bottle hero with screen-space refraction baked into a thickness map. Volume scattering approximated with a 3-tap blue-noise dither; looks expensive, costs nothing.",
    stack: ["Thickness map", "Blue-noise SSS", "Glass IOR shader", "GSAP timelines"],
    palette: ["#0b1109", "#a7d96c", "#f7f0d3"],
    thumbStyle: "orb",
  },
  {
    id: "a24-foliage",
    name: "A24 — Foliage (in cinemas)",
    studio: "Hush",
    url: "https://a24.example/foliage",
    year: 2026,
    techniques: ["immersive-storytelling", "scroll-driven"],
    industry: "Film",
    awards: ["FWA", "Awwwards SOTM"],
    mobilePerf: 77,
    loadKb: 1480,
    fps: 50,
    summary:
      "Five-act trailer site where each scroll chapter is a unique post-processing stack: chromatic split, anamorphic flares, grain LUT, RGB shift, and a final film-burn dissolve.",
    stack: ["EffectComposer stacks", "LUT3D color grade", "Anamorphic lens", "HEVC alpha plates"],
    palette: ["#120000", "#ff4438", "#1a0a05"],
    thumbStyle: "tunnel",
  },
  {
    id: "linear-rooms",
    name: "Linear — Rooms",
    studio: "Linear Brand",
    url: "https://linear.example/rooms",
    year: 2026,
    techniques: ["scroll-driven", "real-time-interactivity"],
    industry: "Tech",
    awards: ["Awwwards SOTD"],
    mobilePerf: 95,
    loadKb: 320,
    fps: 60,
    summary:
      "Pure CSS Houdini Paint API for the gradients; Three.js only runs the hero cube. Total JS shipped: 78KB gz. A lesson in restraint and where 3D actually earns its weight.",
    stack: ["CSS Paint Worklet", "Tiny three-mini", "View Transitions", "Houdini Animation Worklet"],
    palette: ["#0f0f12", "#7f5af0", "#2cb67d"],
    thumbStyle: "grid",
  },
  {
    id: "hermes-cuir",
    name: "Hermès — Cuir Digital",
    studio: "Lusion",
    url: "https://hermes.example/cuir",
    year: 2026,
    techniques: ["product-configuration", "immersive-storytelling"],
    industry: "Fashion",
    awards: ["Awwwards SOTM", "FWA"],
    mobilePerf: 81,
    loadKb: 1320,
    fps: 55,
    summary:
      "Microsuede shader with measured BRDF data from Mitsuba. Stitching simulated via parallax-occlusion maps; hand-painted normal maps swap per leather grade.",
    stack: ["Measured BRDF LUT", "Parallax occlusion", "8K seamless suede", "Color-managed display-P3"],
    palette: ["#1d0e08", "#c08552", "#f6efe7"],
    thumbStyle: "ribbon",
  },
  {
    id: "wmf-protocol",
    name: "WMF — Protocol Zero",
    studio: "Locomotive",
    url: "https://wmf.example/protocol",
    year: 2026,
    techniques: ["scroll-driven"],
    industry: "Crypto",
    awards: ["Codrops Hot"],
    mobilePerf: 87,
    loadKb: 460,
    fps: 60,
    summary:
      "Brutalist scrollytell with a wireframe Voronoi shader as the only 3D element. ScrollSmoother + GSAP MatchMedia keeps motion off entirely on prefers-reduced-motion.",
    stack: ["Voronoi shader", "Wireframe + grain", "Lenis", "MatchMedia gates"],
    palette: ["#000", "#fff", "#ff5b04"],
    thumbStyle: "noise",
  },
  {
    id: "kojima-deep",
    name: "Kojima Productions — DEEP",
    studio: "Production Type",
    url: "https://kojima.example/deep",
    year: 2026,
    techniques: ["immersive-storytelling", "real-time-interactivity"],
    industry: "Gaming",
    awards: ["FWA", "Awwwards SOTM"],
    mobilePerf: 72,
    loadKb: 3080,
    fps: 45,
    summary:
      "Bathysphere descent with real-time god-rays, Beer-Lambert fog, and triplanar wet rock. Streaming geometry chunks unload behind the camera frustum.",
    stack: ["Beer-Lambert fog", "Triplanar mapping", "Streaming meshlets", "Reverb impulse-response audio"],
    palette: ["#000b14", "#1a6f8e", "#88c8ff"],
    thumbStyle: "tunnel",
  },
  {
    id: "rapha-cobble",
    name: "Rapha — Cobble Reads",
    studio: "Resn",
    url: "https://rapha.example/cobble",
    year: 2025,
    techniques: ["scroll-driven", "immersive-storytelling"],
    industry: "Sports",
    awards: ["Awwwards SOTD", "CSSDA"],
    mobilePerf: 90,
    loadKb: 420,
    fps: 60,
    summary:
      "Cobblestone displacement scrubbed via scroll position. Single 1024² heightmap, 16K instanced quads, vertex-shader rotation per stone. Cheap and convincing.",
    stack: ["Heightmap displacement", "Instanced quads", "GSAP scrollTrigger", "AVIF heroes"],
    palette: ["#1a1a1a", "#ec1c24", "#e3dccf"],
    thumbStyle: "grid",
  },
  {
    id: "spotify-yearfeed",
    name: "Spotify — Year-Feed 2026",
    studio: "Spotify Design",
    url: "https://spotify.example/yearfeed",
    year: 2026,
    techniques: ["real-time-interactivity", "scroll-driven"],
    industry: "Music",
    awards: ["Awwwards SOTD"],
    mobilePerf: 93,
    loadKb: 290,
    fps: 60,
    summary:
      "Personalized 3D card stack — pulled per user from edge functions, rendered as a single InstancedMesh of 365 daily tiles. Each tile's UV maps to a CDN-delivered atlas slice.",
    stack: ["InstancedMesh", "Edge personalization", "Atlas slicing", "Pointer events tweens"],
    palette: ["#000", "#1ed760", "#f37aff"],
    thumbStyle: "shards",
  },
  {
    id: "ferrari-vinaccia",
    name: "Ferrari — Vinaccia 750",
    studio: "Immersive Garage",
    url: "https://ferrari.example/vinaccia",
    year: 2026,
    techniques: ["product-configuration"],
    industry: "Automotive",
    awards: ["FWA", "Awwwards SOTM"],
    mobilePerf: 76,
    loadKb: 2120,
    fps: 50,
    summary:
      "Carpaint shader with three-lobe Cook-Torrance and screen-space reflections. Studio HDRI replaced at noon/dusk/night via blendshapes on a single equirect.",
    stack: ["3-lobe Cook-Torrance", "SSR", "HDRI blend", "USDZ AR handoff"],
    palette: ["#0c0c0c", "#ff2800", "#f6f6f6"],
    thumbStyle: "ribbon",
  },
  {
    id: "newport-folly",
    name: "Newport Folly Festival",
    studio: "Field.io",
    url: "https://newport.example/folly",
    year: 2026,
    techniques: ["immersive-storytelling"],
    industry: "Architecture",
    awards: ["Codrops Hot", "OFFF Pick"],
    mobilePerf: 79,
    loadKb: 910,
    fps: 54,
    summary:
      "Procedural pavilion generated in-browser from a parametric script. Wasm-compiled CGAL runs the boolean ops once, caches result IDB-side for repeat visits.",
    stack: ["WASM CGAL", "IndexedDB cache", "BVH picking", "Shader-based wireframe"],
    palette: ["#0d0c0a", "#ffae00", "#fff9e8"],
    thumbStyle: "shards",
  },
  {
    id: "perfume-stage",
    name: "Perfume — Plasma Stage",
    studio: "Rhizomatiks",
    url: "https://perfume.example/plasma",
    year: 2026,
    techniques: ["real-time-interactivity", "immersive-storytelling"],
    industry: "Music",
    awards: ["Awwwards SOTM", "FWA"],
    mobilePerf: 83,
    loadKb: 780,
    fps: 58,
    summary:
      "Three.js + WebMIDI duet: incoming MIDI from the live stream warps a volumetric plasma. SDF particle field driven by a compute pass on WebGPU; canvas fallback for iOS Safari.",
    stack: ["WebMIDI", "Compute particles", "Volumetric SDF", "WebRTC livesync"],
    palette: ["#04020a", "#ff3df6", "#42e0ff"],
    thumbStyle: "particles",
  },
  {
    id: "wired-30",
    name: "Wired — Issue 34.1",
    studio: "Wired Editorial",
    url: "https://wired.example/34-1",
    year: 2026,
    techniques: ["scroll-driven"],
    industry: "Editorial",
    awards: ["Codrops Hot", "Awwwards SOTD"],
    mobilePerf: 92,
    loadKb: 340,
    fps: 60,
    summary:
      "Headline typography extruded as MSDF text in a single draw call. Article images warp through a single fluid distortion shader as you scroll into them.",
    stack: ["MSDF text", "Fluid distortion shader", "Image-as-texture pipeline", "Reduced-motion safe"],
    palette: ["#101010", "#ff0033", "#fafafa"],
    thumbStyle: "ribbon",
  },
  {
    id: "epic-megajam",
    name: "Epic — Megajam Gallery",
    studio: "Epic Games",
    url: "https://epic.example/megajam",
    year: 2026,
    techniques: ["real-time-interactivity"],
    industry: "Gaming",
    awards: ["FWA"],
    mobilePerf: 75,
    loadKb: 1740,
    fps: 48,
    summary:
      "1,500 community submissions arranged on a spiral gallery. GPU-frustum-culled InstancedMesh with mipmap-streamed thumbnails; only 18 textures resident at any frame.",
    stack: ["GPU culling", "Texture residency budget", "Spatial hash picking", "Pointer-lock fly cam"],
    palette: ["#08070b", "#5d3aff", "#ffce4d"],
    thumbStyle: "grid",
  },
  {
    id: "muji-tatami",
    name: "Muji — Tatami Room",
    studio: "Studio Yorktown",
    url: "https://muji.example/tatami",
    year: 2026,
    techniques: ["immersive-storytelling", "scroll-driven"],
    industry: "Editorial",
    awards: ["Awwwards SOTD", "CSSDA"],
    mobilePerf: 97,
    loadKb: 180,
    fps: 60,
    summary:
      "The minimal benchmark. One mesh, one matcap, one scroll-driven camera spline. Ships 180KB gz total and runs at locked 60fps on a 2018 iPhone SE.",
    stack: ["MatCap material", "Camera spline", "Zero post-processing", "View Transitions"],
    palette: ["#f6f3ec", "#1a1a1a", "#a08962"],
    thumbStyle: "noise",
  },
  {
    id: "porsche-mission",
    name: "Porsche — Mission X.1",
    studio: "Achtung!",
    url: "https://porsche.example/mission-x1",
    year: 2025,
    techniques: ["product-configuration", "immersive-storytelling"],
    industry: "Automotive",
    awards: ["Awwwards SOTM", "FWA"],
    mobilePerf: 80,
    loadKb: 1560,
    fps: 52,
    summary:
      "Carbon weave with a custom anisotropic shader sampled at four angles per fragment. Variant geometry deltas streamed as 12KB JSON patches.",
    stack: ["Anisotropic carbon", "Geometry delta patches", "HDR studio LUT", "Tone-mapped HDR"],
    palette: ["#0a0a0a", "#cf0a2c", "#d8d8d8"],
    thumbStyle: "shards",
  },
  {
    id: "the-met-cabinet",
    name: "The Met — Cabinet of Echoes",
    studio: "Potion",
    url: "https://metmuseum.example/cabinet",
    year: 2026,
    techniques: ["immersive-storytelling", "real-time-interactivity"],
    industry: "Editorial",
    awards: ["Awwwards SOTM", "FWA", "CSSDA"],
    mobilePerf: 85,
    loadKb: 740,
    fps: 56,
    summary:
      "47 photogrammetry-scanned objects in a virtual vitrine. Gaussian splat fallback for older Android; mesh+PBR for newer. Pointer-down focus uses depth pre-pass to blur background.",
    stack: ["Gaussian splatting", "Photogrammetry meshes", "Depth pre-pass DOF", "Pointer-based focus"],
    palette: ["#0d0a07", "#caa45a", "#f4ead2"],
    thumbStyle: "orb",
  },
  {
    id: "google-arts-bloom",
    name: "Google Arts — Bloom Engine",
    studio: "Google Creative Lab",
    url: "https://artsandculture.example/bloom",
    year: 2026,
    techniques: ["real-time-interactivity"],
    industry: "Tech",
    awards: ["Awwwards SOTD"],
    mobilePerf: 91,
    loadKb: 480,
    fps: 60,
    summary:
      "L-system flora grown live from a sketch. The user's strokes become control points; geometry shader fakes ribbon stems, particle billboards bloom petals.",
    stack: ["L-system parser", "Ribbon geometry", "Billboard particles", "Pointer-stroke graph"],
    palette: ["#070710", "#ff8ad1", "#84ffc9"],
    thumbStyle: "particles",
  },
  {
    id: "ny-grid-2026",
    name: "NY Times — Grid 2026",
    studio: "NYT R&D",
    url: "https://nyt.example/grid",
    year: 2026,
    techniques: ["scroll-driven"],
    industry: "Editorial",
    awards: ["Awwwards SOTD", "Codrops Hot"],
    mobilePerf: 96,
    loadKb: 220,
    fps: 60,
    summary:
      "Census visualization with 2.1M points rendered as instanced quads. Quantized positions in a 16-bit Float16Array; a single shader does Mercator on the GPU.",
    stack: ["Float16 attributes", "GPU Mercator", "Single draw call", "View Transitions chapters"],
    palette: ["#0b0b0b", "#ffd24a", "#1c8cff"],
    thumbStyle: "grid",
  },
];
